language: go
go:
  - 1.8

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install -v
  - go get -u github.com/jteeuwen/go-bindata/...

addons:
  artifacts:
    paths:
      - out/clairctl-darwin-386
      - out/clairctl-darwin-amd64
      - out/clairctl-linux-386
      - out/clairctl-linux-amd64
    target_paths: latest
    working_dir: out

script:
- go generate ./clair
- go get github.com/mitchellh/gox
- gox -os="linux" -os="darwin" -arch="amd64 386" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-X github.com/ContinuousSecurityTooling/clairctl/cmd.version=$(cat VERSION)"
